language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

branches:
  only:
    - feature/capgen

install:
  - pip install pylint

script:
  - env PYTHONPATH=scripts:${PYTHONPATH} pylint --rcfile ./test/.pylintrc ./tests/test_metadata_table.py
  - env PYTHONPATH=scripts:${PYTHONPATH} pylint --rcfile ./test/.pylintrc ./tests/test_metadata_scheme_file.py
  - python test/unit_tests/test_metadata_table.py
  - python test/unit_tests/test_metadata_scheme_file.py

notifications:
  email:
    recipients:
      - schramm@ucar.edu
    on_success: always # default: change
    on_failure: always # default: always
