name: Capgen Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [feature/capgen, main]

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        fortran-compiler: [gfortran-9, gfortran-10, gfortran-11, gfortran-12, gfortran-13, gfortran-14]
        exclude:
          - os: ubuntu-24.04
            fortran-compiler: gfortran-9
          - os: ubuntu-24.04
            fortran-compiler: gfortran-10
          - os: ubuntu-24.04
            fortran-compiler: gfortran-11
          - os: ubuntu-22.04
            fortran-compiler: gfortran-13	    
          - os: ubuntu-22.04
            fortran-compiler: gfortran-14
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: update repos and install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential ${{matrix.fortran-compiler}} cmake python3 git
    - name: Run unit tests
      run: cd test && ./run_fortran_tests.sh

